# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: unit test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest
    services:

      redis:
        image: mirror.gcr.io/redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.2'
        cache-dependency-path: go.sum

    - name: install govulncheck utility
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: scan for vulnerable packages
      run: make vuln

    - name: run unit test
      env:
        REDIS_URL: redis://127.0.0.1:6379
      run: make test
